[package]
name = "container-gui"
version = "0.3.1"
description = "Real-time Docker GUI"
authors = ["KafkaWannaFly"]
edition = "2024"

[lib]
name = "container_gui_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2.11", features = [] }
tauri-plugin-opener = "2"
tauri-plugin-dialog = "2"
tauri-plugin-pilot = "0.7"
tauri-plugin-log = "2"
log = "0.4"
tokio = { version = "1.53", features = ["full"] }
bollard = { version = "0.21", features = ["pipe", "ssl", "chrono"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
sha2 = "0.11"
bon = "3.10"
tap = "1.0"
variantly = "0.4"
futures-util = "0.3"
astral-tokio-tar = "0.7.0"
tokio-util = { version = "0.7.19", features = ["io"] }
sqlx = { version = "0.9.0", default-features = false, features = ["sqlite-bundled", "runtime-tokio", "macros", "migrate"] }

[dev-dependencies]
tokio = { version = "1.53", features = ["full", "test-util"] }

# Read the optimization guideline for more details: https://tauri.app/concept/size/#cargo-configuration
[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true
